package net.minecraft.item;

import net.minecraft.Bootstrap;
import net.minecraft.resource.Identifier;

public class Items {
    public static final Item IRON_SHOVEL;
    public static final Item IRON_PICKAXE;
    public static final Item IRON_AXE;
    public static final Item FLINT_AND_STEEL;
    public static final Item APPLE;
    public static final BowItem BOW;
    public static final Item ARROW;
    public static final Item COAL;
    public static final Item DIAMOND;
    public static final Item IRON_INGOT;
    public static final Item GOLD_INGOT;
    public static final Item IRON_SWORD;
    public static final Item WOODEN_SWORD;
    public static final Item WOODEN_SHOVEL;
    public static final Item WOODEN_PICKAXE;
    public static final Item WOODEN_AXE;
    public static final Item STONE_SWORD;
    public static final Item STONE_SHOVEL;
    public static final Item STONE_PICKAXE;
    public static final Item STONE_AXE;
    public static final Item DIAMOND_SWORD;
    public static final Item DIAMOND_SHOVEL;
    public static final Item DIAMOND_PICKAXE;
    public static final Item DIAMOND_AXE;
    public static final Item STICK;
    public static final Item BOWL;
    public static final Item MUSHROOM_STEW;
    public static final Item GOLDEN_SWORD;
    public static final Item GOLDEN_SHOVEL;
    public static final Item GOLDEN_PICKAXE;
    public static final Item GOLDEN_AXE;
    public static final Item STRING;
    public static final Item FEATHER;
    public static final Item GUNPOWDER;
    public static final Item WOODEN_HOE;
    public static final Item STONE_HOE;
    public static final Item IRON_HOE;
    public static final Item DIAMOND_HOE;
    public static final Item GOLDEN_HOE;
    public static final Item WHEAT_SEEDS;
    public static final Item WHEAT;
    public static final Item BREAD;
    public static final ArmorItem LEATHER_HELMET;
    public static final ArmorItem LEATHER_CHESTPLATE;
    public static final ArmorItem LEATHER_LEGGINGS;
    public static final ArmorItem LEATHER_BOOTS;
    public static final ArmorItem CHAINMAIL_HELMET;
    public static final ArmorItem CHAINMAIL_CHESTPLATE;
    public static final ArmorItem CHAINMAIL_LEGGINGS;
    public static final ArmorItem CHAINMAIL_BOOTS;
    public static final ArmorItem IRON_HELMET;
    public static final ArmorItem IRON_CHESTPLATE;
    public static final ArmorItem IRON_LEGGINGS;
    public static final ArmorItem IRON_BOOTS;
    public static final ArmorItem DIAMOND_HELMET;
    public static final ArmorItem DIAMOND_CHESTPLATE;
    public static final ArmorItem DIAMOND_LEGGINGS;
    public static final ArmorItem DIAMOND_BOOTS;
    public static final ArmorItem GOLDEN_HELMET;
    public static final ArmorItem GOLDEN_CHESTPLATE;
    public static final ArmorItem GOLDEN_LEGGINGS;
    public static final ArmorItem GOLDEN_BOOTS;
    public static final Item FLINT;
    public static final Item PORKCHOP;
    public static final Item COOKED_PORKCHOP;
    public static final Item PAINTING;
    public static final Item GOLDEN_APPLE;
    public static final Item SIGN;
    public static final Item WOODEN_DOOR;
    public static final Item SPRUCE_DOOR;
    public static final Item BIRCH_DOOR;
    public static final Item JUNGLE_DOOR;
    public static final Item ACACIA_DOOR;
    public static final Item DARK_OAK_DOOR;
    public static final Item BUCKET;
    public static final Item WATER_BUCKET;
    public static final Item LAVA_BUCKET;
    public static final Item MINECART;
    public static final Item SADDLE;
    public static final Item IRON_DOOR;
    public static final Item REDSTONE;
    public static final Item SNOWBALL;
    public static final Item BOAT;
    public static final Item LEATHER;
    public static final Item MILK_BUCKET;
    public static final Item BRICK;
    public static final Item CLAY_BALL;
    public static final Item REEDS;
    public static final Item PAPER;
    public static final Item BOOK;
    public static final Item SLIME_BALL;
    public static final Item CHEST_MINECART;
    public static final Item FURNACE_MINECART;
    public static final Item EGG;
    public static final Item COMPASS;
    public static final FishingRodItem FISHING_ROD;
    public static final Item CLOCK;
    public static final Item GLOWSTONE_DUST;
    public static final Item FISH;
    public static final Item COOKED_FISH;
    public static final Item DYE;
    public static final Item BONE;
    public static final Item SUGAR;
    public static final Item CAKE;
    public static final Item BED;
    public static final Item REPEATER;
    public static final Item COOKIE;
    public static final FilledMapItem FILLED_MAP;
    public static final ShearsItem SHEARS;
    public static final Item MELON;
    public static final Item PUMPKIN_SEEDS;
    public static final Item MELON_SEEDS;
    public static final Item BEEF;
    public static final Item COOKED_BEEF;
    public static final Item CHICKEN;
    public static final Item COOKED_CHICKEN;
    public static final Item MUTTON;
    public static final Item COOKED_MUTTON;
    public static final Item RABBIT;
    public static final Item COOKED_RABBIT;
    public static final Item RABBIT_STEW;
    public static final Item RABBIT_FOOT;
    public static final Item RABBIT_HIDE;
    public static final Item ROTTEN_FLESH;
    public static final Item ENDER_PEARL;
    public static final Item BLAZE_ROD;
    public static final Item GHAST_TEAR;
    public static final Item GOLD_NUGGET;
    public static final Item NETHER_WART;
    public static final PotionItem POTION;
    public static final Item GLASS_BOTTLE;
    public static final Item SPIDER_EYE;
    public static final Item FERMENTED_SPIDER_EYE;
    public static final Item BLAZE_POWDER;
    public static final Item MAGMA_CREAM;
    public static final Item BREWING_STAND;
    public static final Item CAULDRON;
    public static final Item ENDER_EYE;
    public static final Item SPECKLED_MELON;
    public static final Item SPAWN_EGG;
    public static final Item EXPERIENCE_BOTTLE;
    public static final Item FIRE_CHARGE;
    public static final Item WRITABLE_BOOK;
    public static final Item WRITTEN_BOOK;
    public static final Item EMERALD;
    public static final Item ITEM_FRAME;
    public static final Item FLOWER_POT;
    public static final Item CARROT;
    public static final Item POTATO;
    public static final Item BAKED_POTATO;
    public static final Item POISONOUS_POTATO;
    public static final EmptyMapItem EMPTY_MAP;
    public static final Item GOLDEN_CARROT;
    public static final Item SKULL;
    public static final Item CARROT_ON_A_STICK;
    public static final Item NETHER_STAR;
    public static final Item PUMPKIN_PIE;
    public static final Item FIREWORKS;
    public static final Item FIREWORKS_CHARGE;
    public static final EnchantedBookItem ENCHANTED_BOOK;
    public static final Item COMPARATOR;
    public static final Item NETHERBRICK;
    public static final Item QUARTZ;
    public static final Item TNT_MINECART;
    public static final Item HOPPER_MINECART;
    public static final ArmorStandItem ARMOR_STAND;
    public static final Item IRON_HORSE_ARMOR;
    public static final Item GOLDEN_HORSE_ARMOR;
    public static final Item DIAMOND_HORSE_ARMOR;
    public static final Item LEAD;
    public static final Item NAME_TAG;
    public static final Item COMMAND_BLOCK_MINECART;
    public static final Item RECORD_13;
    public static final Item RECORD_CAT;
    public static final Item RECORD_BLOCKS;
    public static final Item RECORD_CHIRP;
    public static final Item RECORD_FAR;
    public static final Item RECORD_MALL;
    public static final Item RECORD_MELLOHI;
    public static final Item RECORD_STAL;
    public static final Item RECORD_STRAD;
    public static final Item RECORD_WARD;
    public static final Item RECORD_11;
    public static final Item RECORD_WAIT;
    public static final Item PRISMARINE_SHARD;
    public static final Item PRISMARINE_CRYSTALS;
    public static final Item BANNER;

    private static Item getOrThrow(String key) {
        return Item.REGISTRY.get(new Identifier(key));
    }

    static {
        if (!Bootstrap.isInitialized()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }

        IRON_SHOVEL = getOrThrow("iron_shovel");
        IRON_PICKAXE = getOrThrow("iron_pickaxe");
        IRON_AXE = getOrThrow("iron_axe");
        FLINT_AND_STEEL = getOrThrow("flint_and_steel");
        APPLE = getOrThrow("apple");
        BOW = (BowItem)getOrThrow("bow");
        ARROW = getOrThrow("arrow");
        COAL = getOrThrow("coal");
        DIAMOND = getOrThrow("diamond");
        IRON_INGOT = getOrThrow("iron_ingot");
        GOLD_INGOT = getOrThrow("gold_ingot");
        IRON_SWORD = getOrThrow("iron_sword");
        WOODEN_SWORD = getOrThrow("wooden_sword");
        WOODEN_SHOVEL = getOrThrow("wooden_shovel");
        WOODEN_PICKAXE = getOrThrow("wooden_pickaxe");
        WOODEN_AXE = getOrThrow("wooden_axe");
        STONE_SWORD = getOrThrow("stone_sword");
        STONE_SHOVEL = getOrThrow("stone_shovel");
        STONE_PICKAXE = getOrThrow("stone_pickaxe");
        STONE_AXE = getOrThrow("stone_axe");
        DIAMOND_SWORD = getOrThrow("diamond_sword");
        DIAMOND_SHOVEL = getOrThrow("diamond_shovel");
        DIAMOND_PICKAXE = getOrThrow("diamond_pickaxe");
        DIAMOND_AXE = getOrThrow("diamond_axe");
        STICK = getOrThrow("stick");
        BOWL = getOrThrow("bowl");
        MUSHROOM_STEW = getOrThrow("mushroom_stew");
        GOLDEN_SWORD = getOrThrow("golden_sword");
        GOLDEN_SHOVEL = getOrThrow("golden_shovel");
        GOLDEN_PICKAXE = getOrThrow("golden_pickaxe");
        GOLDEN_AXE = getOrThrow("golden_axe");
        STRING = getOrThrow("string");
        FEATHER = getOrThrow("feather");
        GUNPOWDER = getOrThrow("gunpowder");
        WOODEN_HOE = getOrThrow("wooden_hoe");
        STONE_HOE = getOrThrow("stone_hoe");
        IRON_HOE = getOrThrow("iron_hoe");
        DIAMOND_HOE = getOrThrow("diamond_hoe");
        GOLDEN_HOE = getOrThrow("golden_hoe");
        WHEAT_SEEDS = getOrThrow("wheat_seeds");
        WHEAT = getOrThrow("wheat");
        BREAD = getOrThrow("bread");
        LEATHER_HELMET = (ArmorItem)getOrThrow("leather_helmet");
        LEATHER_CHESTPLATE = (ArmorItem)getOrThrow("leather_chestplate");
        LEATHER_LEGGINGS = (ArmorItem)getOrThrow("leather_leggings");
        LEATHER_BOOTS = (ArmorItem)getOrThrow("leather_boots");
        CHAINMAIL_HELMET = (ArmorItem)getOrThrow("chainmail_helmet");
        CHAINMAIL_CHESTPLATE = (ArmorItem)getOrThrow("chainmail_chestplate");
        CHAINMAIL_LEGGINGS = (ArmorItem)getOrThrow("chainmail_leggings");
        CHAINMAIL_BOOTS = (ArmorItem)getOrThrow("chainmail_boots");
        IRON_HELMET = (ArmorItem)getOrThrow("iron_helmet");
        IRON_CHESTPLATE = (ArmorItem)getOrThrow("iron_chestplate");
        IRON_LEGGINGS = (ArmorItem)getOrThrow("iron_leggings");
        IRON_BOOTS = (ArmorItem)getOrThrow("iron_boots");
        DIAMOND_HELMET = (ArmorItem)getOrThrow("diamond_helmet");
        DIAMOND_CHESTPLATE = (ArmorItem)getOrThrow("diamond_chestplate");
        DIAMOND_LEGGINGS = (ArmorItem)getOrThrow("diamond_leggings");
        DIAMOND_BOOTS = (ArmorItem)getOrThrow("diamond_boots");
        GOLDEN_HELMET = (ArmorItem)getOrThrow("golden_helmet");
        GOLDEN_CHESTPLATE = (ArmorItem)getOrThrow("golden_chestplate");
        GOLDEN_LEGGINGS = (ArmorItem)getOrThrow("golden_leggings");
        GOLDEN_BOOTS = (ArmorItem)getOrThrow("golden_boots");
        FLINT = getOrThrow("flint");
        PORKCHOP = getOrThrow("porkchop");
        COOKED_PORKCHOP = getOrThrow("cooked_porkchop");
        PAINTING = getOrThrow("painting");
        GOLDEN_APPLE = getOrThrow("golden_apple");
        SIGN = getOrThrow("sign");
        WOODEN_DOOR = getOrThrow("wooden_door");
        SPRUCE_DOOR = getOrThrow("spruce_door");
        BIRCH_DOOR = getOrThrow("birch_door");
        JUNGLE_DOOR = getOrThrow("jungle_door");
        ACACIA_DOOR = getOrThrow("acacia_door");
        DARK_OAK_DOOR = getOrThrow("dark_oak_door");
        BUCKET = getOrThrow("bucket");
        WATER_BUCKET = getOrThrow("water_bucket");
        LAVA_BUCKET = getOrThrow("lava_bucket");
        MINECART = getOrThrow("minecart");
        SADDLE = getOrThrow("saddle");
        IRON_DOOR = getOrThrow("iron_door");
        REDSTONE = getOrThrow("redstone");
        SNOWBALL = getOrThrow("snowball");
        BOAT = getOrThrow("boat");
        LEATHER = getOrThrow("leather");
        MILK_BUCKET = getOrThrow("milk_bucket");
        BRICK = getOrThrow("brick");
        CLAY_BALL = getOrThrow("clay_ball");
        REEDS = getOrThrow("reeds");
        PAPER = getOrThrow("paper");
        BOOK = getOrThrow("book");
        SLIME_BALL = getOrThrow("slime_ball");
        CHEST_MINECART = getOrThrow("chest_minecart");
        FURNACE_MINECART = getOrThrow("furnace_minecart");
        EGG = getOrThrow("egg");
        COMPASS = getOrThrow("compass");
        FISHING_ROD = (FishingRodItem)getOrThrow("fishing_rod");
        CLOCK = getOrThrow("clock");
        GLOWSTONE_DUST = getOrThrow("glowstone_dust");
        FISH = getOrThrow("fish");
        COOKED_FISH = getOrThrow("cooked_fish");
        DYE = getOrThrow("dye");
        BONE = getOrThrow("bone");
        SUGAR = getOrThrow("sugar");
        CAKE = getOrThrow("cake");
        BED = getOrThrow("bed");
        REPEATER = getOrThrow("repeater");
        COOKIE = getOrThrow("cookie");
        FILLED_MAP = (FilledMapItem)getOrThrow("filled_map");
        SHEARS = (ShearsItem)getOrThrow("shears");
        MELON = getOrThrow("melon");
        PUMPKIN_SEEDS = getOrThrow("pumpkin_seeds");
        MELON_SEEDS = getOrThrow("melon_seeds");
        BEEF = getOrThrow("beef");
        COOKED_BEEF = getOrThrow("cooked_beef");
        CHICKEN = getOrThrow("chicken");
        COOKED_CHICKEN = getOrThrow("cooked_chicken");
        MUTTON = getOrThrow("mutton");
        COOKED_MUTTON = getOrThrow("cooked_mutton");
        RABBIT = getOrThrow("rabbit");
        COOKED_RABBIT = getOrThrow("cooked_rabbit");
        RABBIT_STEW = getOrThrow("rabbit_stew");
        RABBIT_FOOT = getOrThrow("rabbit_foot");
        RABBIT_HIDE = getOrThrow("rabbit_hide");
        ROTTEN_FLESH = getOrThrow("rotten_flesh");
        ENDER_PEARL = getOrThrow("ender_pearl");
        BLAZE_ROD = getOrThrow("blaze_rod");
        GHAST_TEAR = getOrThrow("ghast_tear");
        GOLD_NUGGET = getOrThrow("gold_nugget");
        NETHER_WART = getOrThrow("nether_wart");
        POTION = (PotionItem)getOrThrow("potion");
        GLASS_BOTTLE = getOrThrow("glass_bottle");
        SPIDER_EYE = getOrThrow("spider_eye");
        FERMENTED_SPIDER_EYE = getOrThrow("fermented_spider_eye");
        BLAZE_POWDER = getOrThrow("blaze_powder");
        MAGMA_CREAM = getOrThrow("magma_cream");
        BREWING_STAND = getOrThrow("brewing_stand");
        CAULDRON = getOrThrow("cauldron");
        ENDER_EYE = getOrThrow("ender_eye");
        SPECKLED_MELON = getOrThrow("speckled_melon");
        SPAWN_EGG = getOrThrow("spawn_egg");
        EXPERIENCE_BOTTLE = getOrThrow("experience_bottle");
        FIRE_CHARGE = getOrThrow("fire_charge");
        WRITABLE_BOOK = getOrThrow("writable_book");
        WRITTEN_BOOK = getOrThrow("written_book");
        EMERALD = getOrThrow("emerald");
        ITEM_FRAME = getOrThrow("item_frame");
        FLOWER_POT = getOrThrow("flower_pot");
        CARROT = getOrThrow("carrot");
        POTATO = getOrThrow("potato");
        BAKED_POTATO = getOrThrow("baked_potato");
        POISONOUS_POTATO = getOrThrow("poisonous_potato");
        EMPTY_MAP = (EmptyMapItem)getOrThrow("map");
        GOLDEN_CARROT = getOrThrow("golden_carrot");
        SKULL = getOrThrow("skull");
        CARROT_ON_A_STICK = getOrThrow("carrot_on_a_stick");
        NETHER_STAR = getOrThrow("nether_star");
        PUMPKIN_PIE = getOrThrow("pumpkin_pie");
        FIREWORKS = getOrThrow("fireworks");
        FIREWORKS_CHARGE = getOrThrow("firework_charge");
        ENCHANTED_BOOK = (EnchantedBookItem)getOrThrow("enchanted_book");
        COMPARATOR = getOrThrow("comparator");
        NETHERBRICK = getOrThrow("netherbrick");
        QUARTZ = getOrThrow("quartz");
        TNT_MINECART = getOrThrow("tnt_minecart");
        HOPPER_MINECART = getOrThrow("hopper_minecart");
        ARMOR_STAND = (ArmorStandItem)getOrThrow("armor_stand");
        IRON_HORSE_ARMOR = getOrThrow("iron_horse_armor");
        GOLDEN_HORSE_ARMOR = getOrThrow("golden_horse_armor");
        DIAMOND_HORSE_ARMOR = getOrThrow("diamond_horse_armor");
        LEAD = getOrThrow("lead");
        NAME_TAG = getOrThrow("name_tag");
        COMMAND_BLOCK_MINECART = getOrThrow("command_block_minecart");
        RECORD_13 = getOrThrow("record_13");
        RECORD_CAT = getOrThrow("record_cat");
        RECORD_BLOCKS = getOrThrow("record_blocks");
        RECORD_CHIRP = getOrThrow("record_chirp");
        RECORD_FAR = getOrThrow("record_far");
        RECORD_MALL = getOrThrow("record_mall");
        RECORD_MELLOHI = getOrThrow("record_mellohi");
        RECORD_STAL = getOrThrow("record_stal");
        RECORD_STRAD = getOrThrow("record_strad");
        RECORD_WARD = getOrThrow("record_ward");
        RECORD_11 = getOrThrow("record_11");
        RECORD_WAIT = getOrThrow("record_wait");
        PRISMARINE_SHARD = getOrThrow("prismarine_shard");
        PRISMARINE_CRYSTALS = getOrThrow("prismarine_crystals");
        BANNER = getOrThrow("banner");
    }
}
