package net.minecraft.block;

import net.minecraft.Bootstrap;
import net.minecraft.resource.Identifier;

public class Blocks {
    public static final Block AIR;
    public static final Block STONE;
    public static final GrassBlock GRASS;
    public static final Block DIRT;
    public static final Block COBBLESTONE;
    public static final Block PLANKS;
    public static final Block SAPLING;
    public static final Block BEDROCK;
    public static final FlowingLiquidBlock FLOWING_WATER;
    public static final LiquidSourceBlock WATER;
    public static final FlowingLiquidBlock FLOWING_LAVA;
    public static final LiquidSourceBlock LAVA;
    public static final SandBlock SAND;
    public static final Block GRAVEL;
    public static final Block GOLD_ORE;
    public static final Block IRON_ORE;
    public static final Block COAL_ORE;
    public static final Block LOG;
    public static final Block LOG2;
    public static final AbstractLeavesBlock LEAVES;
    public static final AbstractLeavesBlock LEAVES2;
    public static final Block SPONGE;
    public static final Block GLASS;
    public static final Block LAPIS_ORE;
    public static final Block LAPIS_BLOCK;
    public static final Block DISPENSER;
    public static final Block SANDSTONE;
    public static final Block NOTEBLOCK;
    public static final Block BED;
    public static final Block POWERED_RAIL;
    public static final Block DETECTOR_RAIL;
    public static final PistonBaseBlock STICKY_PISTON;
    public static final Block WEB;
    public static final TallPlantBlock TALLGRASS;
    public static final DeadBushBlock DEADBUSH;
    public static final PistonBaseBlock PISTON;
    public static final PistonHeadBlock PISTON_HEAD;
    public static final Block WOOL;
    public static final MovingBlock MOVING_BLOCK;
    public static final FlowerBlock YELLOW_FLOWER;
    public static final FlowerBlock RED_FLOWER;
    public static final PlantBlock BROWN_MUSHROOM;
    public static final PlantBlock RED_MUSHROOM;
    public static final Block GOLD_BLOCK;
    public static final Block IRON_BLOCK;
    public static final SlabBlock DOUBLE_STONE_SLAB;
    public static final SlabBlock STONE_SLAB;
    public static final Block BRICKS;
    public static final Block TNT;
    public static final Block BOOKSHELF;
    public static final Block MOSSY_COBBLESTONE;
    public static final Block OBSIDIAN;
    public static final Block TORCH;
    public static final FireBlock FIRE;
    public static final Block MOB_SPAWNER;
    public static final Block OAK_STAIRS;
    public static final ChestBlock CHEST;
    public static final RedstoneWireBlock REDSTONE_WIRE;
    public static final Block DIAMOND_ORE;
    public static final Block DIAMOND_BLOCK;
    public static final Block CRAFTING_TABLE;
    public static final Block WHEAT;
    public static final Block FARMLAND;
    public static final Block FURNACE;
    public static final Block LIT_FURNACE;
    public static final Block STANDING_SIGN;
    public static final Block WOODEN_DOOR;
    public static final Block SPRUCE_DOOR;
    public static final Block BIRCH_DOOR;
    public static final Block JUNGLE_DOOR;
    public static final Block ACACIA_DOOR;
    public static final Block DARK_OAK_DOOR;
    public static final Block LADDER;
    public static final Block RAIL;
    public static final Block STONE_STAIRS;
    public static final Block WALL_SIGN;
    public static final Block LEVER;
    public static final Block STONE_PRESSURE_PLATE;
    public static final Block IRON_DOOR;
    public static final Block WOODEN_PRESSURE_PLATE;
    public static final Block REDSTONE_ORE;
    public static final Block LIT_REDSTONE_ORE;
    public static final Block UNLIT_REDSTONE_TORCH;
    public static final Block REDSTONE_TORCH;
    public static final Block STONE_BUTTON;
    public static final Block SNOW_LAYER;
    public static final Block ICE;
    public static final Block SNOW;
    public static final CactusBlock CACTUS;
    public static final Block CLAY;
    public static final SugarCaneBlock REEDS;
    public static final Block JUKEBOX;
    public static final Block FENCE;
    public static final Block SPRUCE_FENCE;
    public static final Block BIRCH_FENCE;
    public static final Block JUNGLE_FENCE;
    public static final Block DARK_OAK_FENCE;
    public static final Block ACACIA_FENCE;
    public static final Block PUMPKIN;
    public static final Block NETHERRACK;
    public static final Block SOUL_SAND;
    public static final Block GLOWSTONE;
    public static final PortalBlock NETHER_PORTAL;
    public static final Block LIT_PUMPKIN;
    public static final Block CAKE;
    public static final RepeaterBlock REPEATER;
    public static final RepeaterBlock POWERED_REPEATER;
    public static final Block TRAPDOOR;
    public static final Block MONSTER_EGG;
    public static final Block STONE_BRICKS;
    public static final Block BROWN_MUSHROOM_BLOCK;
    public static final Block RED_MUSHROOM_BLOCK;
    public static final Block IRON_BARS;
    public static final Block GLASS_PANE;
    public static final Block MELON_BLOCK;
    public static final Block PUMPKIN_STEM;
    public static final Block MELON_STEM;
    public static final Block VINE;
    public static final Block FENCE_GATE;
    public static final Block SPRUCE_FENCE_GATE;
    public static final Block BIRCH_FENCE_GATE;
    public static final Block JUNGLE_FENCE_GATE;
    public static final Block DARK_OAK_FENCE_GATE;
    public static final Block ACACIA_FENCE_GATE;
    public static final Block BRICK_STAIRS;
    public static final Block STONE_BRICK_STAIRS;
    public static final MyceliumBlock MYCELIUM;
    public static final Block LILY_PAD;
    public static final Block NETHER_BRICKS;
    public static final Block NETHER_BRICK_FENCE;
    public static final Block NETHER_BRICK_STAIRS;
    public static final Block NETHER_WART;
    public static final Block ENCHANTING_TABLE;
    public static final Block BREWING_STAND;
    public static final CauldronBlock CAULDRON;
    public static final Block END_PORTAL;
    public static final Block END_PORTAL_FRAME;
    public static final Block END_STONE;
    public static final Block DRAGON_EGG;
    public static final Block REDSTONE_LAMP;
    public static final Block LIT_REDSTONE_LAMP;
    public static final SlabBlock DOUBLE_WOODEN_SLAB;
    public static final SlabBlock WOODEN_SLAB;
    public static final Block COCOA;
    public static final Block SANDSTONE_STAIRS;
    public static final Block EMERALD_ORE;
    public static final Block ENDER_CHEST;
    public static final TripwireHookBlock TRIPWIRE_HOOK;
    public static final Block TRIPWIRE;
    public static final Block EMERALD_BLOCK;
    public static final Block SPRUCE_STAIRS;
    public static final Block BIRCH_STAIRS;
    public static final Block JUNGLE_STAIRS;
    public static final Block COMMAND_BLOCK;
    public static final BeaconBlock BEACON;
    public static final Block COBBLESTONE_WALL;
    public static final Block FLOWER_POT;
    public static final Block CARROTS;
    public static final Block POTATOES;
    public static final Block WOODEN_BUTTON;
    public static final SkullBlock SKULL;
    public static final Block ANVIL;
    public static final Block TRAPPED_CHEST;
    public static final Block LIGHT_WEIGHTED_PRESSURE_PLATE;
    public static final Block HEAVY_WEIGHTED_PRESSURE_PLATE;
    public static final ComparatorBlock COMPARATOR;
    public static final ComparatorBlock POWERED_COMPARATOR;
    public static final DaylightDetectorBlock DAYLIGHT_DETECTOR;
    public static final DaylightDetectorBlock INVERTED_DAYLIGHT_DETECTOR;
    public static final Block REDSTONE_BLOCK;
    public static final Block QUARTZ_ORE;
    public static final HopperBlock HOPPER;
    public static final Block QUARTZ_BLOCK;
    public static final Block QUARTZ_STAIRS;
    public static final Block ACTIVATOR_RAIL;
    public static final Block DROPPER;
    public static final Block STAINED_HARDENED_CLAY;
    public static final Block BARRIER;
    public static final Block IRON_TRAPDOOR;
    public static final Block HAY;
    public static final Block CARPET;
    public static final Block HARDENED_CLAY;
    public static final Block COAL_BLOCK;
    public static final Block PACKED_ICE;
    public static final Block ACACIA_STAIRS;
    public static final Block DARK_OAK_STAIRS;
    public static final Block SLIME;
    public static final DoublePlantBlock DOUBLE_PLANT;
    public static final StainedGlassBlock STAINED_GLASS;
    public static final StainedGlassPaneBlock STAINED_GLASS_PANE;
    public static final Block PRISMARINE;
    public static final Block SEA_LANTERN;
    public static final Block STANDING_BANNER;
    public static final Block WALL_BANNER;
    public static final Block RED_SANDSTONE;
    public static final Block RED_SANDSTONE_STAIRS;
    public static final SlabBlock DOUBLE_RED_SANDSTONE_SLAB;
    public static final SlabBlock RED_SANDSTONE_SLAB;

    private static Block getOrThrow(String key) {
        return Block.REGISTRY.get(new Identifier(key));
    }

    static {
        if (!Bootstrap.isInitialized()) {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }

        AIR = getOrThrow("air");
        STONE = getOrThrow("stone");
        GRASS = (GrassBlock)getOrThrow("grass");
        DIRT = getOrThrow("dirt");
        COBBLESTONE = getOrThrow("cobblestone");
        PLANKS = getOrThrow("planks");
        SAPLING = getOrThrow("sapling");
        BEDROCK = getOrThrow("bedrock");
        FLOWING_WATER = (FlowingLiquidBlock)getOrThrow("flowing_water");
        WATER = (LiquidSourceBlock)getOrThrow("water");
        FLOWING_LAVA = (FlowingLiquidBlock)getOrThrow("flowing_lava");
        LAVA = (LiquidSourceBlock)getOrThrow("lava");
        SAND = (SandBlock)getOrThrow("sand");
        GRAVEL = getOrThrow("gravel");
        GOLD_ORE = getOrThrow("gold_ore");
        IRON_ORE = getOrThrow("iron_ore");
        COAL_ORE = getOrThrow("coal_ore");
        LOG = getOrThrow("log");
        LOG2 = getOrThrow("log2");
        LEAVES = (AbstractLeavesBlock)getOrThrow("leaves");
        LEAVES2 = (AbstractLeavesBlock)getOrThrow("leaves2");
        SPONGE = getOrThrow("sponge");
        GLASS = getOrThrow("glass");
        LAPIS_ORE = getOrThrow("lapis_ore");
        LAPIS_BLOCK = getOrThrow("lapis_block");
        DISPENSER = getOrThrow("dispenser");
        SANDSTONE = getOrThrow("sandstone");
        NOTEBLOCK = getOrThrow("noteblock");
        BED = getOrThrow("bed");
        POWERED_RAIL = getOrThrow("golden_rail");
        DETECTOR_RAIL = getOrThrow("detector_rail");
        STICKY_PISTON = (PistonBaseBlock)getOrThrow("sticky_piston");
        WEB = getOrThrow("web");
        TALLGRASS = (TallPlantBlock)getOrThrow("tallgrass");
        DEADBUSH = (DeadBushBlock)getOrThrow("deadbush");
        PISTON = (PistonBaseBlock)getOrThrow("piston");
        PISTON_HEAD = (PistonHeadBlock)getOrThrow("piston_head");
        WOOL = getOrThrow("wool");
        MOVING_BLOCK = (MovingBlock)getOrThrow("piston_extension");
        YELLOW_FLOWER = (FlowerBlock)getOrThrow("yellow_flower");
        RED_FLOWER = (FlowerBlock)getOrThrow("red_flower");
        BROWN_MUSHROOM = (PlantBlock)getOrThrow("brown_mushroom");
        RED_MUSHROOM = (PlantBlock)getOrThrow("red_mushroom");
        GOLD_BLOCK = getOrThrow("gold_block");
        IRON_BLOCK = getOrThrow("iron_block");
        DOUBLE_STONE_SLAB = (SlabBlock)getOrThrow("double_stone_slab");
        STONE_SLAB = (SlabBlock)getOrThrow("stone_slab");
        BRICKS = getOrThrow("brick_block");
        TNT = getOrThrow("tnt");
        BOOKSHELF = getOrThrow("bookshelf");
        MOSSY_COBBLESTONE = getOrThrow("mossy_cobblestone");
        OBSIDIAN = getOrThrow("obsidian");
        TORCH = getOrThrow("torch");
        FIRE = (FireBlock)getOrThrow("fire");
        MOB_SPAWNER = getOrThrow("mob_spawner");
        OAK_STAIRS = getOrThrow("oak_stairs");
        CHEST = (ChestBlock)getOrThrow("chest");
        REDSTONE_WIRE = (RedstoneWireBlock)getOrThrow("redstone_wire");
        DIAMOND_ORE = getOrThrow("diamond_ore");
        DIAMOND_BLOCK = getOrThrow("diamond_block");
        CRAFTING_TABLE = getOrThrow("crafting_table");
        WHEAT = getOrThrow("wheat");
        FARMLAND = getOrThrow("farmland");
        FURNACE = getOrThrow("furnace");
        LIT_FURNACE = getOrThrow("lit_furnace");
        STANDING_SIGN = getOrThrow("standing_sign");
        WOODEN_DOOR = getOrThrow("wooden_door");
        SPRUCE_DOOR = getOrThrow("spruce_door");
        BIRCH_DOOR = getOrThrow("birch_door");
        JUNGLE_DOOR = getOrThrow("jungle_door");
        ACACIA_DOOR = getOrThrow("acacia_door");
        DARK_OAK_DOOR = getOrThrow("dark_oak_door");
        LADDER = getOrThrow("ladder");
        RAIL = getOrThrow("rail");
        STONE_STAIRS = getOrThrow("stone_stairs");
        WALL_SIGN = getOrThrow("wall_sign");
        LEVER = getOrThrow("lever");
        STONE_PRESSURE_PLATE = getOrThrow("stone_pressure_plate");
        IRON_DOOR = getOrThrow("iron_door");
        WOODEN_PRESSURE_PLATE = getOrThrow("wooden_pressure_plate");
        REDSTONE_ORE = getOrThrow("redstone_ore");
        LIT_REDSTONE_ORE = getOrThrow("lit_redstone_ore");
        UNLIT_REDSTONE_TORCH = getOrThrow("unlit_redstone_torch");
        REDSTONE_TORCH = getOrThrow("redstone_torch");
        STONE_BUTTON = getOrThrow("stone_button");
        SNOW_LAYER = getOrThrow("snow_layer");
        ICE = getOrThrow("ice");
        SNOW = getOrThrow("snow");
        CACTUS = (CactusBlock)getOrThrow("cactus");
        CLAY = getOrThrow("clay");
        REEDS = (SugarCaneBlock)getOrThrow("reeds");
        JUKEBOX = getOrThrow("jukebox");
        FENCE = getOrThrow("fence");
        SPRUCE_FENCE = getOrThrow("spruce_fence");
        BIRCH_FENCE = getOrThrow("birch_fence");
        JUNGLE_FENCE = getOrThrow("jungle_fence");
        DARK_OAK_FENCE = getOrThrow("dark_oak_fence");
        ACACIA_FENCE = getOrThrow("acacia_fence");
        PUMPKIN = getOrThrow("pumpkin");
        NETHERRACK = getOrThrow("netherrack");
        SOUL_SAND = getOrThrow("soul_sand");
        GLOWSTONE = getOrThrow("glowstone");
        NETHER_PORTAL = (PortalBlock)getOrThrow("portal");
        LIT_PUMPKIN = getOrThrow("lit_pumpkin");
        CAKE = getOrThrow("cake");
        REPEATER = (RepeaterBlock)getOrThrow("unpowered_repeater");
        POWERED_REPEATER = (RepeaterBlock)getOrThrow("powered_repeater");
        TRAPDOOR = getOrThrow("trapdoor");
        MONSTER_EGG = getOrThrow("monster_egg");
        STONE_BRICKS = getOrThrow("stonebrick");
        BROWN_MUSHROOM_BLOCK = getOrThrow("brown_mushroom_block");
        RED_MUSHROOM_BLOCK = getOrThrow("red_mushroom_block");
        IRON_BARS = getOrThrow("iron_bars");
        GLASS_PANE = getOrThrow("glass_pane");
        MELON_BLOCK = getOrThrow("melon_block");
        PUMPKIN_STEM = getOrThrow("pumpkin_stem");
        MELON_STEM = getOrThrow("melon_stem");
        VINE = getOrThrow("vine");
        FENCE_GATE = getOrThrow("fence_gate");
        SPRUCE_FENCE_GATE = getOrThrow("spruce_fence_gate");
        BIRCH_FENCE_GATE = getOrThrow("birch_fence_gate");
        JUNGLE_FENCE_GATE = getOrThrow("jungle_fence_gate");
        DARK_OAK_FENCE_GATE = getOrThrow("dark_oak_fence_gate");
        ACACIA_FENCE_GATE = getOrThrow("acacia_fence_gate");
        BRICK_STAIRS = getOrThrow("brick_stairs");
        STONE_BRICK_STAIRS = getOrThrow("stone_brick_stairs");
        MYCELIUM = (MyceliumBlock)getOrThrow("mycelium");
        LILY_PAD = getOrThrow("waterlily");
        NETHER_BRICKS = getOrThrow("nether_brick");
        NETHER_BRICK_FENCE = getOrThrow("nether_brick_fence");
        NETHER_BRICK_STAIRS = getOrThrow("nether_brick_stairs");
        NETHER_WART = getOrThrow("nether_wart");
        ENCHANTING_TABLE = getOrThrow("enchanting_table");
        BREWING_STAND = getOrThrow("brewing_stand");
        CAULDRON = (CauldronBlock)getOrThrow("cauldron");
        END_PORTAL = getOrThrow("end_portal");
        END_PORTAL_FRAME = getOrThrow("end_portal_frame");
        END_STONE = getOrThrow("end_stone");
        DRAGON_EGG = getOrThrow("dragon_egg");
        REDSTONE_LAMP = getOrThrow("redstone_lamp");
        LIT_REDSTONE_LAMP = getOrThrow("lit_redstone_lamp");
        DOUBLE_WOODEN_SLAB = (SlabBlock)getOrThrow("double_wooden_slab");
        WOODEN_SLAB = (SlabBlock)getOrThrow("wooden_slab");
        COCOA = getOrThrow("cocoa");
        SANDSTONE_STAIRS = getOrThrow("sandstone_stairs");
        EMERALD_ORE = getOrThrow("emerald_ore");
        ENDER_CHEST = getOrThrow("ender_chest");
        TRIPWIRE_HOOK = (TripwireHookBlock)getOrThrow("tripwire_hook");
        TRIPWIRE = getOrThrow("tripwire");
        EMERALD_BLOCK = getOrThrow("emerald_block");
        SPRUCE_STAIRS = getOrThrow("spruce_stairs");
        BIRCH_STAIRS = getOrThrow("birch_stairs");
        JUNGLE_STAIRS = getOrThrow("jungle_stairs");
        COMMAND_BLOCK = getOrThrow("command_block");
        BEACON = (BeaconBlock)getOrThrow("beacon");
        COBBLESTONE_WALL = getOrThrow("cobblestone_wall");
        FLOWER_POT = getOrThrow("flower_pot");
        CARROTS = getOrThrow("carrots");
        POTATOES = getOrThrow("potatoes");
        WOODEN_BUTTON = getOrThrow("wooden_button");
        SKULL = (SkullBlock)getOrThrow("skull");
        ANVIL = getOrThrow("anvil");
        TRAPPED_CHEST = getOrThrow("trapped_chest");
        LIGHT_WEIGHTED_PRESSURE_PLATE = getOrThrow("light_weighted_pressure_plate");
        HEAVY_WEIGHTED_PRESSURE_PLATE = getOrThrow("heavy_weighted_pressure_plate");
        COMPARATOR = (ComparatorBlock)getOrThrow("unpowered_comparator");
        POWERED_COMPARATOR = (ComparatorBlock)getOrThrow("powered_comparator");
        DAYLIGHT_DETECTOR = (DaylightDetectorBlock)getOrThrow("daylight_detector");
        INVERTED_DAYLIGHT_DETECTOR = (DaylightDetectorBlock)getOrThrow("daylight_detector_inverted");
        REDSTONE_BLOCK = getOrThrow("redstone_block");
        QUARTZ_ORE = getOrThrow("quartz_ore");
        HOPPER = (HopperBlock)getOrThrow("hopper");
        QUARTZ_BLOCK = getOrThrow("quartz_block");
        QUARTZ_STAIRS = getOrThrow("quartz_stairs");
        ACTIVATOR_RAIL = getOrThrow("activator_rail");
        DROPPER = getOrThrow("dropper");
        STAINED_HARDENED_CLAY = getOrThrow("stained_hardened_clay");
        BARRIER = getOrThrow("barrier");
        IRON_TRAPDOOR = getOrThrow("iron_trapdoor");
        HAY = getOrThrow("hay_block");
        CARPET = getOrThrow("carpet");
        HARDENED_CLAY = getOrThrow("hardened_clay");
        COAL_BLOCK = getOrThrow("coal_block");
        PACKED_ICE = getOrThrow("packed_ice");
        ACACIA_STAIRS = getOrThrow("acacia_stairs");
        DARK_OAK_STAIRS = getOrThrow("dark_oak_stairs");
        SLIME = getOrThrow("slime");
        DOUBLE_PLANT = (DoublePlantBlock)getOrThrow("double_plant");
        STAINED_GLASS = (StainedGlassBlock)getOrThrow("stained_glass");
        STAINED_GLASS_PANE = (StainedGlassPaneBlock)getOrThrow("stained_glass_pane");
        PRISMARINE = getOrThrow("prismarine");
        SEA_LANTERN = getOrThrow("sea_lantern");
        STANDING_BANNER = getOrThrow("standing_banner");
        WALL_BANNER = getOrThrow("wall_banner");
        RED_SANDSTONE = getOrThrow("red_sandstone");
        RED_SANDSTONE_STAIRS = getOrThrow("red_sandstone_stairs");
        DOUBLE_RED_SANDSTONE_SLAB = (SlabBlock)getOrThrow("double_stone_slab2");
        RED_SANDSTONE_SLAB = (SlabBlock)getOrThrow("stone_slab2");
    }
}
